---
name: jason
github_org: jasonkuster
repository: beam
merge_branch: master
verification_branch: mergebot
scm_type: github
jenkins_location: https://35.184.226.36
verification_job_name: beam-merge-1
